/**
 * @description       : 
 * @author            : Akash Arora
 * @group             : 
 * @last modified on  : 05-17-2023
 * @last modified by  : Akash Arora
**/
public with sharing class B2BRecommendedProductsConstant {
   
    public static final String MESSAGING_LOG = 'log';
    public static final String MESSAGING_ENTRY = '[M:E]:';
    public static final String MESSAGING_EXIT = '[M:X]:';
    public static final String MESSAGING_VALUE = '[M:V]:';
    
    public static final String IS_SUCCESS = 'isSuccess' ;
    public static final String MESSAGE = 'message' ;
    public static final String PRODUCT_IDS = 'productIds';
    public static final String PRODUCT_ID_STR = 'productIdStr';
    public static final String RECORD_ID = 'recordId';
    public static final String COMMUNITY_ID = 'communityId';
    public static final String WEB_STORE_ID = 'webStoreId';
    public static final String PAGE_NAME = 'pageName';
    public static final String SORT_BY = 'sortBy';
    public static final String SORT_ORDER = 'sortOrder';
    public static final String LIMIT_SIZE = 'limitSize';
    public static final String PRODUCT_DETAIL_PAGE = 'Product Detail Page';
    public static final String SET_PRODUCT_IDS = 'setProdIds';
    public static final String PRODUCTS_WITH_PRICING = 'productsWithPricing';
    public static final String RECOMMENDED_PRODUCTS = 'recommendedProducts';
    public static final String RECOMMENDED_PRODUCTS_OBJECT = 'recommendedProductsObject';
    public static final String EFFECTIVE_ACCOUNT_ID = 'effectiveAccountId';
    public static final String EFFECTIVE_ACCOUNT = 'effectiveAccount';
    public static final String PRODUCT_VARIATION_PARENT = 'VariationParent';
}